version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: quotes_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=aklfjaoijfaofjoj
      - POSTGRES_USER=postgres
      - POSTGRES_DB=quotesdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - quotes_network

networks:
  quotes_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local